### Numpy属性

In [2]:
import numpy as np

a = np.arange(15).reshape(3, 5)
# arange,生成一维矩阵
print('矩阵形状:', a.shape)
print('矩阵维数：', a.ndim)
print('矩阵元素类型:', a.dtype)
print('矩阵元素大小:', a.itemsize)
print('矩阵大小:', a.size)
print('矩阵类型:', type(a))

矩阵形状: (3, 5)
矩阵维数： 2
矩阵元素类型: int64
矩阵元素大小: 8
矩阵大小: 15
矩阵类型: <class 'numpy.ndarray'>


### ndarray

In [3]:
a = np.array([2, 3, 4])
print("数组a元素类型:",a)
print("数组a类型:", a.dtype)

b = np.array([1.2, 3.5, 5.1])
print("数组b元素类型:", b.dtype)

数组a元素类型: [2 3 4]
数组a类型: int64
数组b元素类型: float64


In [4]:
np_arange =np.arange(10, 20, 5, dtype=int)
print("arange创建np_arange:", np_arange)
print("arange创建np_arange的元素类型:", np_arange.dtype)
print("arange创建np_arange的类型:", type(np_arange))

arange创建np_arange: [10 15]
arange创建np_arange的元素类型: int64
arange创建np_arange的类型: <class 'numpy.ndarray'>


### 随机数矩阵

In [5]:
arr = np.random.rand(3, 4) 
print(arr)
print(type(arr)) 

arr = np.random.randint(-1, 5, size=(3, 4))
print(arr)
print(type(arr))

arr =np.random.uniform(-1, 5, size=(3, 4))
print(arr)
print(type(arr))

[[0.35044314 0.65798539 0.99296445 0.24771821]
 [0.28502387 0.26252981 0.75075858 0.73864707]
 [0.28950111 0.25361076 0.65181271 0.02733405]]
<class 'numpy.ndarray'>
[[-1  3  4  3]
 [ 4  1  0  0]
 [ 4  0  0  0]]
<class 'numpy.ndarray'>
[[ 2.00303999  2.76832212 -0.76791238  2.40767695]
 [ 0.99639993  3.56709139  1.66368187  0.08305198]
 [ 2.36083151  0.81955073  4.36419061  1.51778015]]
<class 'numpy.ndarray'>


### 类型转换

In [6]:
# 初始化3行4列数组，数据类型为f1oat64
zeros_float_arr = np.zeros((3,4),dtype=np.float64)
print(zeros_float_arr)
print(zeros_float_arr.dtype) #float64
# astype转换数据类型，将已有的数组的数据类型转换为int32
zeros_int_arr = zeros_float_arr.astype(np.int32)
print(zeros_int_arr)
print(zeros_int_arr.dtype) #int32

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int32


### 等比等差数列

In [8]:
a = np.logspace(0, 0, 3)
a

array([1., 1., 1.])

In [13]:
b = np.logspace(1, 3, 3, base = 2)
b

array([2., 4., 8.])

In [14]:
c = np.linspace(1, 10, 10)
c

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [16]:
d = np.linspace(1, 11, 10, endpoint=False)
d

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### numpy内置函数

#### 基本函数

In [ ]:
arr = np.random.randn(2,3)
print(arr)

[[-1.13240077 -1.66346924  1.45787939]
 [-0.9250296  -1.65425025  0.19981879]]
[[-1. -1.  2.]
 [-0. -1.  1.]]
[[-2. -2.  1.]
 [-1. -2.  0.]]
[[-1. -2.  1.]
 [-1. -2.  0.]]
[[False False False]
 [False False False]]
[[1.28233151 2.76712992 2.12541232]
 [0.85567977 2.73654391 0.03992755]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[-1 -1  1]
 [-1 -1  1]]


In [ ]:
print(np.ceil(arr))
print(np.floor(arr))
print(np.rint(arr))
print(np.isnan(arr))
print(np.multiply(arr, arr))
print(np.divide(arr, arr))
print(np.where(arr>0, 1, -1))

#### 统计函数

In [19]:
arr = np.arange(12).reshape(3, 4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
print(np.mean(arr))
print(np.mean(arr, axis=0))
print(np.mean(arr, axis=1))
print(np.sum(arr))
print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))
print(np.max(arr))
print(np.max(arr, axis=0))
print(np.max(arr, axis=1))
print(np.min(arr))
print(np.min(arr, axis=0))
print(np.min(arr, axis=1))
print(np.var(arr))
print(np.var(arr, axis=0))
print(np.var(arr, axis=1))

5.5
[4. 5. 6. 7.]
[1.5 5.5 9.5]
66
[12 15 18 21]
[ 6 22 38]
11
[ 8  9 10 11]
[ 3  7 11]
0
[0 1 2 3]
[0 4 8]


In [22]:
print(np.std(arr))
print(np.std(arr, axis=0))
print(np.std(arr, axis=1))
print(np.argmin(arr))
print(np.argmin(arr, axis=0))
print(np.argmin(arr, axis=1))
print(np.argmax(arr))
print(np.argmax(arr, axis=0))
print(np.argmax(arr, axis=1))
print(np.cumsum(arr))
print(np.cumsum(arr, axis=0))
print(np.cumsum(arr, axis=1))
print(np.cumprod(arr))
print(np.cumprod(arr, axis=0))
print(np.cumprod(arr, axis=1))

3.452052529534663
[3.26598632 3.26598632 3.26598632 3.26598632]
[1.11803399 1.11803399 1.11803399]
0
[0 0 0 0]
[0 0 0]
11
[2 2 2 2]
[3 3 3]
[ 0  1  3  6 10 15 21 28 36 45 55 66]
[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]
[0 0 0 0 0 0 0 0 0 0 0 0]
[[  0   1   2   3]
 [  0   5  12  21]
 [  0  45 120 231]]
[[   0    0    0    0]
 [   4   20  120  840]
 [   8   72  720 7920]]
